application:
  name: test

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
