app:
  main:
    pollerFrequency : 5
    pollerCron : '*/10 * * * * *'
    threadPoolSize: 5
    channelPoolSize: 1
    dataIn: C:/outilsDev/projets/server/in
    dataOut: C:/outilsDev/projets/server/out
    fileRegexPattern: .*

application:
  name: test

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, configprops, beans

#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/db
#    username: root
#    password: root
#    driver-class-name: org.mariadb.jdbc.Driver

#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    show-sql: true


